# Generated by Django 4.2.9 on 2024-02-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=20)),
                ('comment', models.CharField(max_length=255)),
                ('text_embeddings', models.TextField()),
                ('img_embeddings', models.TextField()),
                ('cos_sim', models.FloatField()),
            ],
        ),
    ]
